version: '2'

services:
  jitsi_meet-app:
    container_name: jitsi_meet-app
    image: registry.selfdesign.org/docker/jitsi-meet:debian
    volumes:
      - /conf:/etc/prosody/conf.d
      - /certs:/var/lib/prosody
      - /data:/var/lib/data
    environment:
      - VIRTUAL_HOST=example.domain.com
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=example.domain.com
      - LETSENCRYPT_EMAIL=email@Hostname.com

      - LOCAL=local
      - DOMAIN=domain.com
      - PASSWORD=password

      - JITSI_VIDEO_PASS=secret1

      - JICOFO_PASS=secret2
      - JICOFO_USER_PASS=secret3

    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy

