version: '2'

services:
  jitsi_meet-app:
    container_name: jitsi_meet-app
    image: tiredofit/jitsi-meet
    volumes:
      - ./logs:/www/logs
    environment:
      - VIRTUAL_HOST=example.domain.com
      - VIRTUAL_NETWORK=nginx-proxy
      - LETSENCRYPT_HOST=example.domain.com
      - LETSENCRYPT_EMAIL=email@Hostname.com

      - JITSI_VIDEO_PASS=secret1

      - JICOFO_PASS=secret2
      - JICOFO_USER_PASS=secret3

    networks:
      - proxy-tier
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy


